nginx:
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "172.31.97.121:80:80"
node1:
    build: ./node
    links:
        - redis
    ports:
        - "8500"
node2:
    build: ./node
    links:
        - redis
    ports:
        - "8500"
node3:
    build: ./node
    links:
        - redis
    ports:
        - "8500"
redis:
    image: redis
    ports:
        - "6379"
